#### Importing Packages

In [22]:
!pip install scikit-learn


In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

##### Load dataset

In [25]:
data = pd.read_csv("Brain_Stroke.csv")

In [26]:
data.shape

(4981, 11)

##### PreProcessing Data

In [27]:
data = data.dropna() # Handle missing values

In [28]:
# Encode categorical variables
le = LabelEncoder()
for col in data.select_dtypes(include=["object"]).columns:
    data[col] = le.fit_transform(data[col])

In [29]:
X = data.drop("stroke", axis=1)
y = data["stroke"]

##### Train-test split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

##### Standard Scaler

In [31]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

##### Models

In [32]:
models = {
"Logistic Regression": LogisticRegression(max_iter=1000),
"SVM": SVC(probability=True),
"Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
"Decision Tree": DecisionTreeClassifier(random_state=42),
"KNN": KNeighborsClassifier(n_neighbors=5)
}

In [33]:
for name, model in models.items():
    print("\n===========================")
    print(f"{name}")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))


Logistic Regression
Accuracy: 0.9458375125376128
Confusion Matrix:
 [[943   0]
 [ 54   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.95      1.00      0.97       943
           1       0.00      0.00      0.00        54

    accuracy                           0.95       997
   macro avg       0.47      0.50      0.49       997
weighted avg       0.89      0.95      0.92       997


SVM


c:\Users\ROHITH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ROHITH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ROHITH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(

Accuracy: 0.9458375125376128
Confusion Matrix:
 [[943   0]
 [ 54   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.95      1.00      0.97       943
           1       0.00      0.00      0.00        54

    accuracy                           0.95       997
   macro avg       0.47      0.50      0.49       997
weighted avg       0.89      0.95      0.92       997


Random Forest


c:\Users\ROHITH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ROHITH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ROHITH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(

Accuracy: 0.9418254764292878
Confusion Matrix:
 [[939   4]
 [ 54   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.95      1.00      0.97       943
           1       0.00      0.00      0.00        54

    accuracy                           0.94       997
   macro avg       0.47      0.50      0.49       997
weighted avg       0.89      0.94      0.92       997


Decision Tree
Accuracy: 0.921765295887663
Confusion Matrix:
 [[908  35]
 [ 43  11]]
Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.96      0.96       943
           1       0.24      0.20      0.22        54

    accuracy                           0.92       997
   macro avg       0.60      0.58      0.59       997
weighted avg       0.92      0.92      0.92       997


KNN
Accuracy: 0.9408224674022067
Confusion Matrix:
 [[937   6]
 [ 53   1]]
Classification Report:
               precision    recall  f1-scor